### ISSUE TITLE
util.js: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by gasxia** [react-component/tree#42]
我把rc-tree组件的源码拿出来，单独放在项目内使用。可是在webpack中报这个错误。
具体是在`handleCheckState()`函数的代码导致的错误。因为我把这个函数注释掉后，就不再报错了。
```
WARNING in ./static/component/outline/outline/tree/util.js
Module build failed: TypeError: F:/jinrunsen/Projects/fansmanage/static/component/outline/outline/tree/util.js: Cannot read property 'file' of undefined
    at Plugin.buildExpressionHandler (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-plugin-import\1.0.1\babel-plugin-import\lib\Plugin.js:49:26)
    at Plugin.ExpressionStatement (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-plugin-import\1.0.1\babel-plugin-import\lib\Plugin.js:204:14)
    at applyInstance (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-plugin-import\1.0.1\babel-plugin-import\lib\index.js:27:26)
    at PluginPass.ret.visitor.(anonymous function) (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-plugin-import\1.0.1\babel-plugin-import\lib\index.js:85:9)
    at newFn (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-traverse\6.18.0\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-traverse\6.18.0\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-traverse\6.18.0\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-traverse\6.18.0\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-traverse\6.18.0\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitMultiple (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-traverse\6.18.0\babel-traverse\lib\context.js:103:17)
    at TraversalContext.visit (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-traverse\6.18.0\babel-traverse\lib\context.js:190:19)
    at Function.traverse.node (F:\jinrunsen\Projects\fansmanage\node_modules\.npminstall\babel-traverse\6.18.0\babel-traverse\lib\index.js:114:17)
 @ ./static/component ^\.\/.*$
```

**Comment by yesmeck** [comment]
提供下你的代码？

**Comment by ltchronus** [comment]
@yesmeck
是配合使用了 babel-plugin-import这个插件
```
  for (let pIndex = 0; pIndex < checkedPositionArr.length; pIndex++) {
    // 循环设置父节点的 选中 或 半选状态
    const loop = (__pos) => {
      const _posLen = splitPosition(__pos).length;
      if (_posLen <= 2) { // e.g. '0-0', '0-1'
        return;
      }
      let sibling = 0;
      let siblingChecked = 0;
      const parentPosition = stripTail(__pos);
      objKeys.forEach((i /* , index*/) => {
        const iArr = splitPosition(i);
        if (iArr.length === _posLen && isInclude(splitPosition(parentPosition), iArr)) {
          sibling++;
          if (obj[i].checked) {
            siblingChecked++;
            const _i = checkedPositionArr.indexOf(i);
            if (_i > -1) {
              checkedPositionArr.splice(_i, 1);
              if (_i <= pIndex) {
                pIndex--;
              }
            }
          } else if (obj[i].halfChecked) {
            siblingChecked += 0.5;
          }
          // objKeys[index] = null;
        }
      });
      // objKeys = objKeys.filter(i => i); // filter non null;
      const parent = obj[parentPosition];
      // sibling 不会等于0
      // 全不选 - 全选 - 半选
      if (siblingChecked === 0) {
        parent.checked = false;
        parent.halfChecked = false;
      } else if (siblingChecked === sibling) {
        parent.checked = true;
        parent.halfChecked = false;
      } else {
        parent.halfChecked = true;
        parent.checked = false;
      }
      loop(parentPosition);
    };
    loop(checkedPositionArr[pIndex], pIndex);
  }
```
中间的pIndex--引起的，好像是AST解析到这里的时候path.hub 是undefined,
我查了[babel plugin文档](https://github.com/thejameskyle/babel-handbook/blob/master/translations/zh-Hans/plugin-handbook.md#toc11)并没有说hub属性是个啥。。
#https://github.com/ant-design/babel-plugin-import/issues/123

**Comment by yesmeck** [comment]
babel-plugin-import 的问题。
